### ISSUE TITLE
PC_SHARP result

### ISSUE THREAD

**Issue by cultivo-hy** [rnakato/DROMPA3#3]
Hi. I'm Lee.

I tried to process other data using DROMPA3 and found a weird thing.

Is there any reason to exclude "chrY" when do a peak calling?

I found it in the result of peak calling and this is because of the code 'dp_main.c' , line 70.

I guess this tries to remove unplaced chromosome. if so, "chrY" should be retained, right?

`70   if(!p->includeYM && (!strcmp(g->chr[chr].name, "chrY") || !strcmp(g->chr[chr].name, "chrM") || !strcmp(g->chr[chr].name, "chrMT"))) return;`

Thanks.

- Lee -

**Comment by rnakato** [comment]
Hi Lee,

Thank you for using DROMPA3.
Yes, DROMPA3 ignores the chromosome Y and mitocondria in default because there are quite a few repetitive regions in them that often cause noisy results.
If you want to include them, please supply "-includeYM" option.

Ryu

**Comment by cultivo-hy** [comment]
Ah, I didn't notice that command in manual.

Thanks.
